services:

  frontend:
    image: node:16.1-alpine3.11
    working_dir: /usr/src/app
    command: npm run docker
    volumes:
      - ./src/OV.React:/usr/src/app
      - ./cfg:/usr/src/app/cfg

  backend:
    image: node:16.1-alpine3.11
    working_dir: /usr/src/app
    command: npm run docker
    ports:
      - "3000:3000"
    volumes:
      - ./src/OV.Node:/usr/src/app
      - ./src/OV.React/dist:/usr/src/app/src/assets
      - ./cfg:/usr/src/app/cfg